import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FAFAFA',
  },
  topBanner: {
    backgroundColor: '#FF6F00',
    paddingTop: 50,
    paddingBottom: 25,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    alignItems: 'center',
    elevation: 8,
  },
  appName: {
    fontSize: 30,
    fontWeight: '900',
    color: '#fff',
    letterSpacing: 1,
  },
  tagline: {
    fontSize: 16,
    color: '#ffe0b2',
    marginTop: 6,
    fontStyle: 'italic',
    textAlign: 'center',
  },
  content: {
    flex: 1,
  },
  scrollArea: {
    padding: 16,
    paddingBottom: 80,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#FF6F00',
    marginVertical: 14,
    marginLeft: 4,
  },
  cardRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 12,
  },
  foodCard: {
    width: '48%',
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 10,
    marginBottom: 16,
    alignItems: 'center',
    elevation: 4,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
  },
  cardImage: {
    width: '100%',
    height: 100,
    borderRadius: 12,
  },
  cardLabel: {
    marginTop: 10,
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
    textAlign: 'center',
  },
  restaurantCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 14,
    marginBottom: 16,
    elevation: 3,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
  },
  restaurantImage: {
    width: '100%',
    height: 130,
    borderRadius: 14,
  },
  restaurantName: {
    fontSize: 18,
    fontWeight: '700',
    marginTop: 10,
    color: '#222',
  },
  restaurantInfo: {
    fontSize: 14,
    color: '#777',
    marginTop: 4,
  },
  orderCard: {
    backgroundColor: '#fff',
    padding: 16,
    borderRadius: 12,
    marginBottom: 20,
    elevation: 3,
    marginHorizontal: 10,
  },
  orderHeading: {
    fontWeight: 'bold',
    fontSize: 16,
    color: '#FF6F00',
    marginBottom: 4,
  },
  orderSub: {
    fontSize: 14,
    marginTop: 6,
    color: '#333',
  },
  orderItem: {
    marginLeft: 10,
    color: '#555',
    fontSize: 13,
  },
  orderAddress: {
    marginTop: 4,
    fontSize: 14,
    color: '#444',
  },
 
    profileCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 20,
    marginHorizontal: 16,
    marginTop: 16,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 4,
  },
  profileAvatar: {
    width: 100,
    height: 100,
    borderRadius: 50,
    marginBottom: 15,
    borderWidth: 2,
    borderColor: '#FF6F00',
  },
  profileInfo: {
    width: '100%',
    paddingHorizontal: 10,
  },
  profileField: {
    fontSize: 15,
    marginBottom: 8,
    color: '#333',
    lineHeight: 22,
  },
  profileLabel: {
    fontWeight: '700',
    color: '#555',
  },
  profileAddress: {
    fontSize: 14,
    color: '#444',
    lineHeight: 20,
    marginBottom: 8,
    marginTop: 4,
  },
  signOutBtn: {
    marginTop: 30,
    backgroundColor: '#FF6F00',
    paddingVertical: 14,
    paddingHorizontal: 50,
    borderRadius: 30,
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 5,
  },
  signOutText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
    letterSpacing: 0.5,
  },

  empty: {
    fontSize: 15,
    color: '#999',
    textAlign: 'center',
    marginTop: 30,
    fontStyle: 'italic',
  },
  bottomNav: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: '#eee',
    backgroundColor: '#fff',
    paddingVertical: 10,
    justifyContent: 'space-around',
    elevation: 12,
  },
  navItem: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  navIcon: {
    width: 26,
    height: 26,
    tintColor: '#bbb',
  },
  navIconActive: {
    tintColor: '#FF6F00',
  },
  navLabel: {
    fontSize: 11,
    marginTop: 2,
    color: '#999',
  },
  navLabelActive: {
    color: '#FF6F00',
    fontWeight: '700',
  },
});
